import { MCQuestion } from "./types";

// STAFF LEVEL — Entry-level team members across hospitality, retail, and service businesses
// Practical scenarios, simple math, daily operations

export const PS_STAFF: MCQuestion[
] = [
  { type: "mc", id: 1, question: "A customer received the wrong order. What should you do FIRST?", options: ["Apologize sincerely while confirm what the customer originally ordered from the menu", "Ask a colleague to check the order ticket before you say anything to the customer", "Offer the customer a full discount on the bill plus let them keep the wrong item", "Inform the customer that order mix-ups happen and assure them it will be corrected"], correct: 0 },
  { type: "mc", id: 2, question: "You notice supplies at your station are running low during a busy period. What should you do?", options: ["Continue working normally and mention the low supplies to the next shift when they arrive", "Stop what you are doing right now and immediately go to the storage room to restock", "Wait until the supplies run out completely before leaving your station to get fresh stock", "Inform your supervisor and quickly restock from backup supplies while keeping tasks going"], correct: 3 },
  { type: "mc", id: 3, question: "A customer purchases 3 items at Rp 35,000 each and 2 items at Rp 85,000 each. What is the subtotal?", options: ["Rp 275,000", "Rp 240,000", "Rp 255,000", "Rp 205,000"], correct: 0 },
  { type: "mc", id: 4, question: "You accidentally damage a customer's personal belongings. What is the best response?", options: ["Apologize immediately while let your supervisor know so they can handle it appropriately", "Offer to pay for the repairs yourself from your salary to demonstrate responsibility here", "Wait to see if the customer notices the damage before you bring it to their attention", "Explain to the customer it was minor and unlikely to cause any permanent lasting damage"], correct: 0 },
  { type: "mc", id: 5, question: "Your business is at full capacity but a walk-in customer asks to be served. What do you say?", options: ["Apologize that you are at capacity and offer to add them to the waitlist with a time estimate", "Tell the customer to try another nearby business, since you will not have space for a while", "Let the customer wait in the front area without giving them any specific estimated wait time", "Suggest they check back later in the evening when there might be an available spot for them"], correct: 0 },
  { type: "mc", id: 6, question: "You see a colleague taking company products without authorization. What should you do?", options: ["Report what you observed to your supervisor in a private conversation for proper handling", "Confront the colleague loudly in front of everyone so they learn that this is not allowed", "Tell other coworkers about the incident so they can also keep a close eye on things now", "Ignore it entirely, because it is not your responsibility and you prefer to avoid conflict"], correct: 0 },
  { type: "mc", id: 7, question: "A task requires 200 grams of material per batch. You need to prepare 5 batches. How much material do you need?", options: ["750g", "1,200g", "1,000g", "500g"], correct: 2 },
  { type: "mc", id: 8, question: "A customer tells you they have a severe allergy. What do you do?", options: ["Note the allergy on the order clearly, alert the relevant team, and verify before serving", "Remove the allergen from their order yourself before serving without telling anyone else", "Tell the customer that most of your products probably do not contain that allergen at all", "Suggest the customer visit a different business that specializes in allergy-safe offerings"], correct: 0 },
  { type: "mc", id: 9, question: "While tidying your work area, you find a customer's personal item they left behind. What do you do?", options: ["Leave it right where you found it, because the customer will probably come back for it soon", "Try to open or look through the item to figure out who owns it and contact them directly", "Turn it in to your supervisor or bring it to the designated lost-and-found area right away", "Put it in your bag for safekeeping until someone comes back and asks you about it later"], correct: 2 },
  { type: "mc", id: 10, question: "Your shift starts at 10:00 AM but you're stuck in traffic and will arrive 15 minutes late. What should you do?", options: ["Contact your supervisor as soon as possible to let them know your expected arrival time", "Ask a coworker to clock in on your behalf so it does not show as late on the system", "Arrive late and just explain the traffic situation to your supervisor when they ask about it", "Call in sick instead of arriving late, because that looks better on your attendance records"], correct: 0 },
  { type: "mc", id: 11, question: "A customer asks about an ingredient or feature you're not sure about. What do you do?", options: ["Say you are unsure but will check with the right person and get back to them quickly", "Give your best guess, so that the customer does not have to wait around for the answer", "Tell the customer you have no idea and suggest they look it up on their own phone instead", "Say no to everything to be safe, because under-promising is better than giving wrong details"], correct: 0 },
  { type: "mc", id: 12, question: "Near the end of your shift, you notice a cleaning task that's been overlooked for a while. What do you do?", options: ["Handle it now because maintaining standards is the responsibility of everyone on every shift", "Cover it up so the next shift will not see it and will just deal with it on their own", "Leave it for the next shift, since your working hours are nearly finished for today anyway", "Pretend you did not notice it, because mentioning it would mean extra work for you tonight"], correct: 0 },
];

export const TM_STAFF: MCQuestion[
] = [
  { type: "mc", id: 1, question: "You arrive for your shift. What should you do FIRST?", options: ["Start serving customers right away so you do not waste any productive working minutes", "Chat with your coworkers about what happened yesterday to catch up on all the latest news", "Go to the break room to have a coffee before starting anything to get yourself fully ready", "Check your station, review any notes from the prior shift, and set up your tools properly"], correct: 3 },
  { type: "mc", id: 2, question: "Three tasks need attention at the same time: Task A is a new customer request, Task B has a time-sensitive item ready for delivery, Task C is a payment request. What order?", options: ["Task A first, then B, then C because new customer requests always take the highest priority", "Task C first, then B, then A because processing payments clears customers the most efficiently", "Task B first since the item will lose quality, then Task A for the customer, then Task C last", "Task B first to prevent quality loss, then Task C for efficient flow, and then Task A after"], correct: 2 },
  { type: "mc", id: 3, question: "You need to complete 6 similar tasks. Your equipment can handle 2 at a time. What's the fastest approach?", options: ["Complete them one by one to ensure that each one gets your full and undivided attention", "Ask another person to help you, so that you can split the total work evenly between the two", "Do all six at once by rushing through them as quickly as you can possibly manage to finish", "Process them in pairs of two and use the wait time between batches to prepare your materials"], correct: 3 },
  { type: "mc", id: 4, question: "Your supervisor assigns you a new task, but you're in the middle of helping a customer. What do you do?", options: ["Stop helping the customer immediately and go do whatever your supervisor just asked of you", "Ignore the supervisor's request entirely, since the customer you are helping is the top priority", "Tell the supervisor you are far too busy to take on any additional work responsibilities now", "Finish helping the customer first and then begin the newly assigned task right away after"], correct: 3 },
  { type: "mc", id: 5, question: "It's 30 minutes before opening and you have three setup tasks: Task A (20 min), Task B (10 min), Task C (5 min). Total is 35 minutes. Can you finish in time?", options: ["No — you should call in extra staff, because there is simply not enough time for all tasks", "Yes — skip Task C entirely, because that one is the least important of the three listed tasks", "No — the tasks clearly add up to thirty-five minutes which is more than the thirty available", "Yes — overlap Task B with Task A while moving between areas to save some time on both"], correct: 3 },
  { type: "mc", id: 6, question: "During a busy period, a regular customer wants to chat. You have several other customers waiting. What do you do?", options: ["Chat with them for a while, because regular customers are important and deserve more attention", "Ignore the regular completely and just serve the other customers without saying anything to them", "Tell the regular to come back when it is less busy, because you cannot talk right now at all", "Politely acknowledge them, explain you will be right back, and serve waiting customers first"], correct: 3 },
  { type: "mc", id: 7, question: "You have closing tasks: mopping (15 min), cash count (10 min), wiping surfaces (10 min), taking out trash (5 min). What order is most efficient?", options: ["Cash first, then surfaces, then trash, then mopping last so the floor stays clean and dries", "Mopping first, then surfaces, then trash, then cash last since the floor takes longest to dry", "Trash first, then surfaces, then cash count, and finally mopping at the very end of closing", "Surfaces first, then mopping, then trash, then cash last to end with the register closing count"], correct: 0 },
  { type: "mc", id: 8, question: "A coworker asks you to cover their station for 5 minutes, but your own station is busy. What do you do?", options: ["Say yes and try to manage both stations at the same time, even though you are stretched thin", "Say no very bluntly without offering any alternative solution or suggestion to help them at all", "Cover their station and ignore yours entirely, since they asked you first and you should help", "Explain your station is busy right now and suggest they ask the supervisor for proper coverage"], correct: 3 },
  { type: "mc", id: 9, question: "A time-sensitive delivery is ready, but you also need to take a new customer's order. The delivery will lose quality if delayed. What's the priority?", options: ["Take the new customer's order first, because it will be quicker and gets them started sooner", "Ask another team member to handle one of the two tasks if someone is available to help now", "Bring out half the delivery, take the customer's order, then bring out the remaining half after", "Handle the time-sensitive delivery right away, then take the new customer's order right after"], correct: 3 },
  { type: "mc", id: 10, question: "You're assigned a back-of-house task, but the customer-facing area gets unexpectedly busy. What do you do?", options: ["Finish the back-of-house task entirely before going out to help any customers at all now", "Complain to the manager that you have too many tasks assigned for just one single person", "Drop the back-of-house task completely and do not return to it for the rest of your shift", "Help the customer area during the busy rush, then finish the back task once it calms down"], correct: 3 },
  { type: "mc", id: 11, question: "You notice a supply station is almost empty while helping a customer. What do you do?", options: ["Stop in the middle of service to refill the station immediately before doing anything else", "Leave it alone, because restocking is not specifically listed as part of your job description", "Finish serving the customer, then refill all supply stations in your section before moving on", "Wait until someone else spots it and let them complain about it before you bother refilling"], correct: 2 },
  { type: "mc", id: 12, question: "Your shift ends at 3 PM but a large group just arrived at 2:45 PM. What should you do?", options: ["Leave at exactly 3 PM, because your shift is over and you are not required to stay longer", "Refuse to help them at all, because they arrived far too close to the end of your work shift", "Take their initial request and hand off to the next team member with a clear proper briefing", "Stay until they are completely finished, even if it means working hours past your shift time"], correct: 2 },
  { type: "mc", id: 13, question: "An important piece of equipment breaks during a busy period. What should you do?", options: ["Stop everything else and try to fix the equipment on your own even without proper training", "Inform your supervisor, then start using an available backup method to keep things moving along", "Wait for a professional repair person to arrive before doing anything else at your work station", "Tell the team to stop using the work area entirely until the broken equipment gets repaired"], correct: 1 },
  { type: "mc", id: 14, question: "You have a 15-minute break but there's a rush of customers. What do you do?", options: ["Take your full break, because you have earned it and need rest to keep performing at your best", "Ask your supervisor if you can delay your break by ten minutes until the customer rush passes", "Skip your break entirely, because the needs of the business always come before personal rest time", "Take a quick five-minute break right now and hope the rush dies down by the time you return"], correct: 1 },
  { type: "mc", id: 15, question: "It's your first week. You've been shown a process once but you're not confident. A customer requests it. What do you do?", options: ["Attempt it completely on your own without any guidance, since you should be able to figure it out", "Ask an experienced coworker to guide you through it or to watch while you perform the process", "Tell the customer that you cannot do it, because you are new and have not learned it fully yet", "Do something different instead and just hope that the customer does not notice the substitution"], correct: 1 },
  { type: "mc", id: 16, question: "Two customers need your help at the same time. One looks impatient, the other is relaxed. Who do you approach first?", options: ["The impatient one, because they are more likely to escalate a complaint if not helped quickly", "The relaxed one, because they will be easier to deal with and you can finish with them sooner", "Whoever is physically closest to you, regardless of how they currently appear to be feeling now", "Acknowledge both with eye contact and a nod, then go to whoever has been waiting the longest"], correct: 3 },
];

export const COMM_STAFF: MCQuestion[
] = [
  { type: "mc", id: 1, question: "A customer asks for your recommendation but you're unsure what's most popular today. What do you say?", options: ["Tell them every item is great and they cannot possibly go wrong with anything on the list", "Mention a personal favorite and offer to check on what today's featured items are for them", "Say that you do not really know, because you just work here and cannot make any suggestions", "Tell them to pick whatever they like, because all options are basically the same quality anyway"], correct: 1 },
  { type: "mc", id: 2, question: "A customer is speaking very quietly and you can't hear their request in the noisy environment. What do you do?", options: ["Guess what they said and proceed based on your best interpretation of their request to save time", "Lean in politely, ask them to repeat their request, and confirm what you heard back to them", "Shout loudly across the counter asking them to speak up, so that everyone around can also hear", "Write down an approximate order and hope that it turns out to be close enough to what they wanted"], correct: 1 },
  { type: "mc", id: 3, question: "Your supervisor gives you feedback: 'You need to work faster during busy periods.' How should you respond?", options: ["Thank them for the feedback and ask if there are specific areas where you can focus on improving", "Say you are already doing your best and there is nothing more you can realistically change at all", "Point out that other team members are also slow so it is unfair to single you out on your own", "Say nothing, walk away, and just continue doing exactly what you have always been doing before now"], correct: 0 },
  { type: "mc", id: 4, question: "A customer's child is running around the business and creating a safety hazard. How do you handle it?", options: ["Tell the child directly to stop running around and to sit down, because they could get hurt badly", "Ignore the situation entirely, because it is not your job to manage other people's young children", "Politely approach the parents and explain the safety concern, plus ask them to keep their child seated", "Complain about the situation to your coworker and hope that somebody else steps in to handle this"], correct: 2 },
  { type: "mc", id: 5, question: "You accidentally gave a customer Rp 10,000 less in change. They haven't noticed yet. What do you do?", options: ["Say nothing, since the customer did not notice and the amount involved is relatively small anyway", "Wait to see if they come back to complain about it before you take any action to correct it", "Approach the customer, apologize for the error, and hand them the correct amount of remaining change", "Tell your supervisor about the shortage but do not personally approach the customer about it yourself"], correct: 2 },
  { type: "mc", id: 6, question: "A coworker is rude to you in front of customers. What's the best response?", options: ["Respond with the same level of rudeness so they know you will not be treated that way publicly", "Stay professional in the moment, do not react in front of customers, and discuss it privately later", "Report them to the manager immediately on the floor right there in front of all the customers now", "Leave the work area to compose yourself and let all the customers wait without service for a while"], correct: 1 },
  { type: "mc", id: 7, question: "A customer asks about something outside your area of knowledge. What do you say?", options: ["Make up a reasonable answer, so that the customer does not think you are completely incompetent here", "Tell them that is not your department and they will need to find another person to help them out", "Tell them you are not sure but you will find the right person to provide an accurate answer now", "Say you have absolutely no idea and suggest they try searching for the information online themselves"], correct: 2 },
  { type: "mc", id: 8, question: "Operations are running 15 minutes behind schedule. A customer asks about their order. What do you tell them?", options: ["Tell them you do not know what is causing the delay, because it is outside your area of control", "Thank them for their patience, explain there is a short delay, and offer something while they wait", "Say it will come whenever it is ready and there is nothing at all you can do to speed things up", "Avoid going near their area until the order is finished, so that you do not have to explain at all"], correct: 1 },
  { type: "mc", id: 9, question: "You overhear a customer expressing dissatisfaction to their companion, not to you directly. Should you intervene?", options: ["No — they did not complain to you directly so it would be intrusive to get yourself involved here", "Approach gently and ask if there is anything you can help with to improve their experience today", "Tell the rest of the team what the customer said so everybody knows but do not talk to them", "Pretend you did not hear a thing and continue with your normal work as if nothing had happened"], correct: 1 },
  { type: "mc", id: 10, question: "At the end of your shift, the next team member asks about your current workload. What's the best handoff?", options: ["Say everything is fine and leave them to figure things out on their own once they start working", "Briefly explain the status of each active task, any pending items, and any special customer requests", "Point at the work area and say good luck without giving them any specific details or useful context", "Write an extremely detailed multi-page report that covers every single thing that happened all shift"], correct: 1 },
  { type: "mc", id: 11, question: "A group of customers is being very loud and disturbing others nearby. How do you approach them?", options: ["Tell them firmly to be quiet immediately or they will have to leave the establishment right now", "Approach with a smile, acknowledge that they are having fun, and politely ask them to lower volume", "Ignore the situation completely, because they are paying customers and you cannot tell them what to do", "Move the other affected customers to a different area instead of confronting the loud group at all"], correct: 1 },
  { type: "mc", id: 12, question: "You're new and unsure whether a particular product or service is available. A customer asks about it. What do you say?", options: ["Say no to be safe, because it is better to turn down a request than give incorrect information", "Admit you are new and have absolutely no idea about anything which is why you cannot help them", "Let them know you want to give accurate information and will check with your team right away now", "Silently hand them the menu or brochure and walk away without offering any verbal help whatsoever"], correct: 2 },
  { type: "mc", id: 13, question: "A customer makes an unusual personal request. Company policy is unclear on it. What do you do?", options: ["Agree right away without checking, since the customer should always receive whatever they have requested", "Refuse outright, because if there is no clear policy covering it then it is probably not allowed here", "Politely say you would be happy to help and that you just need to verify with your supervisor", "Ignore the request entirely and change the subject to something else that you can help them with"], correct: 2 },
  { type: "mc", id: 14, question: "During a team briefing, your supervisor explains a new rule you disagree with. What do you do?", options: ["Argue publicly about it in front of the team, because your perspective deserves to be heard right now", "Follow the rule for now, then approach your supervisor privately afterward to share your own concern", "Ignore the new rule whenever no one is watching, because you personally know a better way to do it", "Complain to your coworkers after the briefing and encourage everyone to also resist the new policy"], correct: 1 },
  { type: "mc", id: 15, question: "A customer gives you a large personal tip, but your company has a tip-sharing policy. What do you do?", options: ["Keep the full amount for yourself, because the customer specifically intended it for you and nobody else", "Split it only with your closest coworker, because the policy seems unfair to high performers like you", "Thank the customer warmly and follow the established company tip-sharing policy as it applies to everyone", "Give the entire amount to the manager and let them decide how to distribute it among the staff"], correct: 2 },
];
