import { MCQuestion, LikertQuestion, TestConfig } from "./types";

export const TEST_CONFIGS: TestConfig[] = [
  { id: "problem-solving", name: "Problem Solving", questionCount: 12, timeMinutes: 9, description: "Analytical thinking and logical reasoning in F&B scenarios", icon: "🧩" },
  { id: "time-management", name: "Time Management", questionCount: 16, timeMinutes: 9, description: "Prioritization and scheduling under pressure", icon: "⏱️" },
  { id: "ocean", name: "Big 5 (OCEAN)", questionCount: 50, timeMinutes: 10, description: "Personality traits assessment", icon: "🧠" },
  { id: "communication", name: "Communication", questionCount: 15, timeMinutes: 8, description: "Written and verbal communication effectiveness", icon: "💬" },
];

export const PROBLEM_SOLVING: MCQuestion[
] = [
  { type: "mc", id: 1, question: "A venue receives 120 reservations for Friday night but only has 80 seats with an average service time of 90 minutes. Operating hours are 6 PM to 11 PM (5 hours). What is the maximum number of reservations they can accommodate?", options: ["160", "120", "80", "200"], correct: 0 },
  { type: "mc", id: 2, question: "Your supply costs have increased by 15%. If you want to maintain a 70% gross margin, and a product currently sells for Rp 55,000, what should the new price be?", options: ["Rp 63,250", "Rp 58,000", "Rp 60,500", "Rp 65,000"], correct: 0 },
  { type: "mc", id: 3, question: "You notice that your location's product waste has increased by 40% over the past month, while sales remained flat. Which investigation would MOST likely identify the root cause?", options: ["Analyze preparation quantities versus actual orders by day of the week for each individual product sold", "Check whether pricing may be discouraging certain customer segments from purchasing particular items offered", "Survey customers to find out if portion sizes or product specifications have changed at all recently", "Review supplier delivery schedules to determine if timing issues alone are causing the excess spoilage"], correct: 0 },
  { type: "mc", id: 4, question: "Three locations report their monthly revenue: Location A = Rp 800M (target Rp 1B), Location B = Rp 1.2B (target Rp 1.5B), Location C = Rp 600M (target Rp 750M). Which location is performing the worst relative to its target?", options: ["Location A, because its absolute shortfall of Rp 200M represents the largest gap in total revenue", "Location B, because its absolute revenue falls Rp 300M short of the highest target that was set right", "Location C, because it has the lowest overall revenue number, even though its target is the lowest", "All three locations are equally behind at 80 percent of their respective targets with the same rate"], correct: 3 },
  { type: "mc", id: 5, question: "A production area makes 50 units per day. On average, 8 units are wasted. If the material cost per unit is Rp 25,000, what is the monthly waste cost (30 days)?", options: ["Rp 6,000,000", "Rp 4,000,000", "Rp 10,000,000", "Rp 7,500,000"], correct: 0 },
  { type: "mc", id: 6, question: "Your operation wants to reduce service time from 25 minutes to 15 minutes. Three bottlenecks are identified: Station A (3 min delay), Station B (5 min delay), Station C (2 min delay). Which approach is most effective?", options: ["Focus improvement efforts on Station B first since it has the single largest delay of all three", "Hire additional staff for every station to reduce wait times across the board evenly and broadly", "Reduce the number of products or services offered, so that the overall workflow is much simpler", "Install faster equipment at all three stations simultaneously to bring every time point down at once"], correct: 0 },
  { type: "mc", id: 7, question: "Customer complaints increased 30% after a major change. 60% mention 'quantity/value,' 25% mention 'quality,' 15% mention 'presentation.' You can only address one issue this week. What do you fix first?", options: ["Quantity or value because it directly affects the largest proportion of the customers complaining now", "Quality, because it has the most long-term impact on customer retention and overall brand loyalty right", "Presentation, because it is the easiest to fix with the least amount of cost and effort needed right", "Revert the entire change back to how things were before and start the whole process over again right"], correct: 0 },
  { type: "mc", id: 8, question: "Staffing: You have 12 team members. Peak hours need 8, regular hours need 4. Peak runs 7 hours total, regular the remaining hours. Each person works an 8-hour shift. What's the minimum number of shifts needed per day?", options: ["12 shifts under the current circumstances as the recommended course of action going forward now", "16 shifts under the current circumstances as the recommended course of action going forward now", "14 shifts under the current circumstances as the recommended course of action going forward now", "More information about shift overlap timing is needed to calculate the answer with full accuracy"], correct: 3 },
  { type: "mc", id: 9, question: "Your delivery partner reports that 15% of orders arrive in poor condition. Your team's records show items leave in good condition. Average delivery time is 35 minutes. What is the most likely issue?", options: ["The packaging or transport method does not adequately protect the product during the delivery trip", "Your quality control equipment is probably miscalibrated and giving inaccurate readings overall", "The delivery partner is probably fabricating complaints to negotiate lower commission rates from you", "Customers are likely exaggerating the condition issues to receive free refunds or replacement products"], correct: 0 },
  { type: "mc", id: 10, question: "You supervise 3 locations. Location A has the highest revenue but lowest profit margin. Location B has medium revenue and medium margin. Location C has the lowest revenue but highest profit margin. If you could only invest in expanding one, which creates the most value?", options: ["Location A, because highest revenue means the most customers and the strongest overall brand presence", "Location B, because balanced performance makes it the safest and most predictable investment to pursue", "Location C because the highest margin means each new customer generates the most profit for business", "Cannot be determined without additional data about the market size and growth potential in each area"], correct: 2 },
  { type: "mc", id: 11, question: "A supplier offers a 10% discount for ordering double your usual quantity. Your current monthly order is Rp 50M. Extra storage costs Rp 2M/month, and 5% of extra stock typically expires. Should you take the deal?", options: ["Yes but the net benefit is only about Rp 500K after accounting for storage while spoilage expenses", "Yes, because the Rp 5M savings is a large amount that clearly outweighs any additional costs incurred", "No, because the combined spoilage and storage costs will result in a net financial loss on balance", "No, because changing established ordering patterns always introduces unnecessary operational risk and trouble"], correct: 0 },
  { type: "mc", id: 12, question: "During a busy period, your main operating system crashes. You have many active orders in progress. What is the FIRST thing you should do?", options: ["Switch to manual processes immediately and keep serving customers without any significant interruption", "Close the business to all new customers until the system has been fully restored and is back up right", "Call the system provider's technical support line to report the issue and request an emergency fix right", "Ask all current customers to settle their accounts with cash payments until the system comes back right"], correct: 0 },
];

export const TIME_MANAGEMENT: MCQuestion[
] = [
  { type: "mc", id: 1, question: "It's Monday morning. You have these tasks: (A) Prepare for a compliance inspection scheduled for Tuesday, (B) Fix critical equipment that's been down since last night, (C) Interview a candidate at 2pm, (D) Review last week's performance report. What do you tackle first?", options: ["Critical equipment repair because it is actively impacting current operations while causing ongoing losses", "Compliance inspection prep, because the deadline is earliest and involves external stakeholders directly", "Candidate interview, because people decisions are always the highest priority in any growing organization", "Performance report review, because understanding last week's data informs all other decisions for today"], correct: 0 },
  { type: "mc", id: 2, question: "You have 4 hours before a major service period begins. A VIP client needs special preparation (1 hour), team briefing isn't done (30 min), a key team member called in sick (need replacement, ~1 hour of calls), and supplies need restocking (45 min). What's your priority order?", options: ["VIP preparation first, then team briefing, then supplies, and finally find the replacement last right", "Find replacement first, then supplies, then VIP preparation, then team briefing at the very end right", "Find replacement first, then VIP preparation, then supplies, then briefing right before service starts", "Team briefing first, then find replacement, then VIP preparation, then supplies restocking to finish"], correct: 2 },
  { type: "mc", id: 3, question: "Your manager asks for a report by end of day. A supplier calls about a pricing dispute that could save Rp 5M/month. A customer posts a 1-star review going viral. What do you handle first?", options: ["The report, because respecting hierarchy and meeting internal deadlines always comes before everything else", "The supplier call, because it represents the biggest ongoing financial impact for the business each month", "The viral review because reputation damage compounds quickly and spreads faster the longer you wait now", "Try to multitask all three simultaneously, because they are all equally important to the business today"], correct: 2 },
  { type: "mc", id: 4, question: "Which task management approach is MOST effective for someone coordinating daily operations?", options: ["Handle tasks as they come in, because flexibility and responsiveness are the most important qualities", "Follow a strict daily schedule with no room for any deviations or changes throughout the whole day", "Use a prioritized list with buffer time built in for the unexpected issues that will inevitably arise", "Delegate everything possible to others and only handle the escalations that actually reach your level"], correct: 2 },
  { type: "mc", id: 5, question: "You're preparing for a new location opening in 2 weeks. Which timeline is most realistic?", options: ["Front-load critical items like permits, equipment, and staffing in week one plus then details in week two", "Do everything in the last three days, because working under deadline pressure produces the best results", "Split all tasks evenly across all fourteen days so nothing gets more or less attention than others right", "Focus on marketing and promotion first, because without customers nothing else matters at all here now"], correct: 0 },
  { type: "mc", id: 6, question: "A team meeting is running 20 minutes over time, but the operations team needs to start preparing for the next period. What do you do?", options: ["Let the meeting keep going until everything is fully covered, because the discussion is clearly important", "Split the group, so that some members leave for operations, while others stay to finish the meeting", "Tell the operations team to start late, since the meeting information is critical for them to receive", "End the meeting now and send the remaining discussion points in a written message to the whole team"], correct: 3 },
  { type: "mc", id: 7, question: "You receive 15 messages from different team members within 30 minutes. How do you handle this?", options: ["Reply to each message immediately as it arrives, so that nobody has to wait for your response at all", "Ignore every single one of them until you have completely free time to sit down and reply to all", "Quickly scan for urgent items, then batch-reply to the rest at a scheduled time you have designated", "Call a group meeting to address everything at once so you do not have to reply individually to each"], correct: 2 },
  { type: "mc", id: 8, question: "Your recurring monthly tasks include: inventory audit, staff reviews, performance analysis, and financial reporting. You consistently run out of time for performance analysis. What's the best solution?", options: ["Work longer hours to fit everything in, even though it will eventually lead to exhaustion and burnout right", "Skip the performance analysis altogether, because it appears to be the least urgent of the four tasks right", "Block dedicated time specifically for performance analysis and protect it from any interruptions that arise", "Delegate all the other tasks to someone else, so that you only have to focus on analysis alone as the"], correct: 2 },
  { type: "mc", id: 9, question: "Two tasks have the same deadline: (A) a routine supply order (30 min), and (B) resolving a customer complaint that could take 1-2 hours. It's 3 PM and both are due by 5 PM. What's your approach?", options: ["Start with the complaint first, because it is more important and has the biggest business impact now", "Ask for deadline extensions on both, because you clearly do not have enough time available right now", "Try to work on both simultaneously by switching back and forth between the two tasks as you need", "Do the supply order first as a quick win, then focus fully on the complaint with remaining time"], correct: 3 },
  { type: "mc", id: 10, question: "How do you handle a week where 3 team members call in sick across different days?", options: ["Work their shifts yourself to make sure everything is covered, regardless of how tired you become", "Close the operation on the days you are short-staffed, because quality will suffer badly if forced", "Maintain an on-call roster and cross-trained backup staff who can step in on short notice reliably", "Hire three temporary workers immediately from an agency, regardless of the cost or training required"], correct: 2 },
  { type: "mc", id: 11, question: "Your boss asks you to implement a new standard operating procedure system. You estimate it will take 40 hours over 4 weeks. What's the best approach?", options: ["Block one full week entirely and complete the entire project in a single concentrated focused effort right", "Hire an outside consultant to handle the entire project so you can focus on existing daily workload right", "Only work on it whenever you happen to have free time in between your other regular daily tasks right now", "Dedicate two hours each morning before operations begin so you make consistent incremental daily progress"], correct: 3 },
  { type: "mc", id: 12, question: "It's the end of the month. You need to: close the books, submit reports, plan next month's promotions, and conduct 6 staff reviews. You have 3 days. What gets done first?", options: ["Staff reviews first, because they affect real people and their motivation for the upcoming work month", "Reports first, because your boss is waiting for them and internal deadlines should never be missed now", "Promotions first, because they directly impact next month's revenue and need sufficient lead time to work", "Close the books first because every other task depends on having accurate financial numbers available"], correct: 3 },
  { type: "mc", id: 13, question: "A critical repair is quoted at 3 days. You have a major event in 5 days. What buffer strategy do you use?", options: ["Trust the three-day quote, since you have two full days of buffer which should be more than enough", "Pay double to rush the repair and guarantee it is done in half the original time quoted to you", "Cancel the event entirely to be safe, because there is too much risk of the repair not finishing", "Plan as if the repair takes four days and prepare a contingency backup plan in case it extends"], correct: 3 },
  { type: "mc", id: 14, question: "You notice you spend 2 hours daily responding to team messages and questions. How do you reclaim some of this time?", options: ["Stop responding to messages entirely and tell the team to figure things out on their own completely", "Create a single group chat for all questions and hope that reduces the total volume of messages right", "Hire a personal assistant whose sole job is managing and responding to all your team messages daily", "Set specific response windows at designated times and communicate this schedule to your entire team"], correct: 3 },
  { type: "mc", id: 15, question: "Which daily routine is most effective for an operations supervisor?", options: ["Arrive when operations start and leave when they end, handling everything reactively as it comes up", "Rotate randomly between morning and evening shifts each week to maintain unpredictability for the team", "Work remotely until midday and then come in person only for the busiest part of the operational day", "Arrive early for planning and review, walk the floor at opening, plus review performance at closing"], correct: 3 },
  { type: "mc", id: 16, question: "You're in the middle of important analytical work when a team member reports an unhappy customer asking for a supervisor. What do you do?", options: ["Finish your analysis first, because the numbers are important and you will lose your train of thought", "Call another supervisor to deal with it, because you should not be interrupted during analytical tasks", "Send the team member back to handle it alone, since you are occupied with higher-priority work now", "Save your work, handle the customer situation personally, then return to your analysis right after"], correct: 3 },
];

export const OCEAN_QUESTIONS: LikertQuestion[] = [
  // Openness (O)
  { type: "likert", id: 1, question: "I enjoy trying new approaches to solve problems at work.", trait: "O", reversed: false },
  { type: "likert", id: 2, question: "I get excited when we introduce new menu items or concepts.", trait: "O", reversed: false },
  { type: "likert", id: 3, question: "I prefer following established procedures rather than experimenting.", trait: "O", reversed: true },
  { type: "likert", id: 4, question: "I'm comfortable with ambiguity and changing plans.", trait: "O", reversed: false },
  { type: "likert", id: 5, question: "I often think about creative ways to improve our operations.", trait: "O", reversed: false },
  { type: "likert", id: 6, question: "I'd rather stick with what works than try something unproven.", trait: "O", reversed: true },
  { type: "likert", id: 7, question: "I enjoy learning about different cuisines and food cultures.", trait: "O", reversed: false },
  { type: "likert", id: 8, question: "I'm open to feedback that challenges my current way of doing things.", trait: "O", reversed: false },
  { type: "likert", id: 9, question: "I find routine tasks boring and look for ways to make them interesting.", trait: "O", reversed: false },
  { type: "likert", id: 10, question: "I prefer clear instructions over open-ended tasks.", trait: "O", reversed: true },
  // Conscientiousness (C)
  { type: "likert", id: 11, question: "I always complete my tasks on time, even when no one is checking.", trait: "C", reversed: false },
  { type: "likert", id: 12, question: "I keep my workspace organized and clean.", trait: "C", reversed: false },
  { type: "likert", id: 13, question: "I sometimes forget to follow up on things I've promised.", trait: "C", reversed: true },
  { type: "likert", id: 14, question: "I create checklists and systems to stay on top of my work.", trait: "C", reversed: false },
  { type: "likert", id: 15, question: "I pay close attention to details in everything I do.", trait: "C", reversed: false },
  { type: "likert", id: 16, question: "I tend to procrastinate on tasks I find unpleasant.", trait: "C", reversed: true },
  { type: "likert", id: 17, question: "I set high standards for myself and my team.", trait: "C", reversed: false },
  { type: "likert", id: 18, question: "I'm reliable — people know they can count on me.", trait: "C", reversed: false },
  { type: "likert", id: 19, question: "I sometimes cut corners when under pressure.", trait: "C", reversed: true },
  { type: "likert", id: 20, question: "I believe consistency is more important than occasional brilliance.", trait: "C", reversed: false },
  // Extraversion (E)
  { type: "likert", id: 21, question: "I feel energized after interacting with customers and staff.", trait: "E", reversed: false },
  { type: "likert", id: 22, question: "I'm comfortable speaking up in group meetings.", trait: "E", reversed: false },
  { type: "likert", id: 23, question: "I prefer working alone rather than in a team.", trait: "E", reversed: true },
  { type: "likert", id: 24, question: "I naturally take charge in group situations.", trait: "E", reversed: false },
  { type: "likert", id: 25, question: "I enjoy networking and meeting new people in the industry.", trait: "E", reversed: false },
  { type: "likert", id: 26, question: "I find it draining to be around people all day.", trait: "E", reversed: true },
  { type: "likert", id: 27, question: "I'm good at motivating my team during busy shifts.", trait: "E", reversed: false },
  { type: "likert", id: 28, question: "I'm comfortable handling conflict face-to-face.", trait: "E", reversed: false },
  { type: "likert", id: 29, question: "I'd rather send a message than have a conversation.", trait: "E", reversed: true },
  { type: "likert", id: 30, question: "I enjoy being in a fast-paced, high-energy environment.", trait: "E", reversed: false },
  // Agreeableness (A)
  { type: "likert", id: 31, question: "I consider other people's feelings before making decisions.", trait: "A", reversed: false },
  { type: "likert", id: 32, question: "I'm willing to compromise to keep the team happy.", trait: "A", reversed: false },
  { type: "likert", id: 33, question: "I don't mind if my decisions make people uncomfortable.", trait: "A", reversed: true },
  { type: "likert", id: 34, question: "I go out of my way to help colleagues, even when it's not my job.", trait: "A", reversed: false },
  { type: "likert", id: 35, question: "I find it easy to forgive mistakes made by team members.", trait: "A", reversed: false },
  { type: "likert", id: 36, question: "I think being liked is less important than being respected.", trait: "A", reversed: true },
  { type: "likert", id: 37, question: "I try to understand why someone is underperforming before taking action.", trait: "A", reversed: false },
  { type: "likert", id: 38, question: "I believe team harmony is essential for success.", trait: "A", reversed: false },
  { type: "likert", id: 39, question: "I prioritize results over relationships when they conflict.", trait: "A", reversed: true },
  { type: "likert", id: 40, question: "I'm patient when training new staff members.", trait: "A", reversed: false },
  // Neuroticism / Emotional Stability (N) — high score = more stable
  { type: "likert", id: 41, question: "I stay calm under pressure, even during the busiest shifts.", trait: "N", reversed: false },
  { type: "likert", id: 42, question: "I don't take criticism personally.", trait: "N", reversed: false },
  { type: "likert", id: 43, question: "I often worry about things going wrong.", trait: "N", reversed: true },
  { type: "likert", id: 44, question: "I can handle multiple problems at once without getting flustered.", trait: "N", reversed: false },
  { type: "likert", id: 45, question: "I bounce back quickly from setbacks.", trait: "N", reversed: false },
  { type: "likert", id: 46, question: "I sometimes feel overwhelmed by the demands of my job.", trait: "N", reversed: true },
  { type: "likert", id: 47, question: "I maintain a positive attitude even when things don't go as planned.", trait: "N", reversed: false },
  { type: "likert", id: 48, question: "I sleep well even when I have big challenges at work.", trait: "N", reversed: false },
  { type: "likert", id: 49, question: "I get frustrated easily when staff don't meet expectations.", trait: "N", reversed: true },
  { type: "likert", id: 50, question: "I'm confident in my ability to handle any situation that comes up.", trait: "N", reversed: false },
];

export const COMMUNICATION: MCQuestion[
] = [
  { type: "mc", id: 1, question: "A customer complains that the product or service they received doesn't match what they expected. Your team insists it was done correctly. What do you say to the customer?", options: ["Explain politely that your team confirms it was done to specification and offer to discuss it further", "Apologize for the experience and offer to redo or replace it right away without making any excuses", "Suggest the customer speak with the team member directly so they can understand how it was prepared", "Offer a partial discount on the bill as a compromise, while explaining the team followed normal procedure"], correct: 1 },
  { type: "mc", id: 2, question: "You need to tell your team that salary increases are frozen this year due to business performance. How do you deliver this?", options: ["Send a message to the group chat with the news and let them process it on their own individual time", "Tell each person individually whenever you happen to see them throughout the work week at the office", "Hold a team meeting, explain the business context transparently, and share the plan to improve results", "Ask HR to send a formal email so the communication comes from an official source rather than from you"], correct: 2 },
  { type: "mc", id: 3, question: "A team member keeps making the same mistake despite being told twice. What's your next step?", options: ["Write them up formally with a documented warning, since verbal corrections clearly have not worked so far", "Show them the correct way, ask them to demonstrate it back, and schedule a follow-up check on them", "Assign them to a completely different task where this specific mistake is not possible to make at all", "Tell a senior team member to keep a constant eye on them and correct them whenever it happens again"], correct: 1 },
  { type: "mc", id: 4, question: "A supplier sends an invoice that's 20% higher than the agreed price. What's the best first communication?", options: ["Refuse to pay the invoice and threaten to switch suppliers if they do not honor the original terms right", "Pay the higher amount to maintain the relationship and bring it up during the next scheduled meeting", "Send a message referencing the agreed price, attach the original agreement, and ask for a clarification", "Escalate immediately to your finance team and let them handle the dispute with the supplier directly"], correct: 2 },
  { type: "mc", id: 5, question: "During a team meeting, two staff members start arguing. What do you do?", options: ["Let them work it out between themselves, because adults should be able to handle their own conflicts right", "Take sides with whoever presents the stronger argument so the team can move forward with a decision right", "Pause the discussion, acknowledge both perspectives openly, and redirect the conversation toward solutions", "End the meeting immediately and tell both people that they need to calm down before meeting tomorrow right"], correct: 2 },
  { type: "mc", id: 6, question: "You need to give negative feedback to a high-performing team member who has been arriving late. How do you approach it?", options: ["Mention it casually during a busy period so it feels less formal and does not create extra tension right", "Have a private conversation acknowledging their strong performance, then address the lateness specifically", "Dock their pay without discussing it first, because actions are more effective than words at correcting", "Wait until the next formal performance review to bring it up along with all other feedback you have right"], correct: 1 },
  { type: "mc", id: 7, question: "A business partner emails you about a collaboration opportunity, but you're unsure about the terms. What do you do?", options: ["Agree immediately, because partnership opportunities are valuable and you do not want to miss this chance", "Ignore the email entirely, because unsolicited partnership offers are typically not worth pursuing at all", "Reply asking for specific terms including costs, duration, and restrictions before making any decision now", "Forward the email to your boss and wait for their instructions before responding to the partner at all right"], correct: 2 },
  { type: "mc", id: 8, question: "You discover a compliance violation at your location. It's not dangerous but violates standard procedure. The responsible person is your longest-serving team member. How do you handle it?", options: ["Look the other way, because they have earned some flexibility after years of loyal and dedicated service", "Address it privately, restate the standard procedure, and document it with the same standards for all", "Make an example of them in front of the whole team so everyone knows the rules apply to everybody right", "Update the procedure to match what they are doing, since their experience likely means a better method"], correct: 1 },
  { type: "mc", id: 9, question: "A customer posts a negative review online saying 'worst service ever, waited 45 minutes.' Your records show it was actually 22 minutes. How do you respond publicly?", options: ["Correct them publicly stating that your records clearly show the order took only twenty-two minutes total", "Respond with empathy, take the feedback seriously, and invite them to continue the conversation privately", "Do not respond at all, because engaging with negative reviews online draws more unwanted public attention", "Offer a free product or service in the public reply to show other readers that you care about them right"], correct: 1 },
  { type: "mc", id: 10, question: "You're presenting monthly results to leadership. Revenue is down 10% but customer satisfaction is up 15%. How do you frame this?", options: ["Lead with the satisfaction improvement to soften the impact of the negative revenue figures for leaders", "Present both numbers honestly, explain any correlation between them, and share your action plan forward", "Focus only on the revenue number, because that is the thing leadership cares about the most right now", "Blame external factors like weather, competition, or the economy for the revenue decline this past month"], correct: 1 },
  { type: "mc", id: 11, question: "A team member comes to you with a personal problem affecting their work. How do you respond?", options: ["Tell them you are sorry but they need to keep personal issues separate from the workplace entirely", "Listen with empathy, ask how you can support them at work, and discuss temporary schedule adjustments", "Immediately refer them to HR, because personal issues are outside the scope of your role as supervisor", "Tell them to take time off until they sort out their personal situation and can return fully focused"], correct: 1 },
  { type: "mc", id: 12, question: "You're briefing new team members before their first shift. What's most important to communicate?", options: ["The company's full history and values so they understand the deeper purpose behind their daily work right", "Key service standards, their specific responsibilities for the shift, and who to ask when they need help", "All the rules and the consequences they will face if they break any of them during their employment right", "A detailed tour of the entire facility covering every room and system before they start doing anything"], correct: 1 },
  { type: "mc", id: 13, question: "You need to coordinate with 3 different departments for a special event. What's the best communication approach?", options: ["Send one group message to everyone involved and assume they will figure out their own department tasks", "Hold a brief joint meeting to align on the plan, then follow up with department-specific details after", "Meet with each department separately three times so you can tailor the message to each team's needs", "Write a detailed email covering everything and assume everyone will read and follow it without question"], correct: 1 },
  { type: "mc", id: 14, question: "A long-time supplier asks you to increase your order this month to help them hit their targets. You don't need the extra inventory. What do you say?", options: ["Simply say no without any explanation, because you do not owe them a reason for business decisions", "Appreciate the relationship but explain you cannot take extra stock, and offer to help another way", "Agree to the increased order, because maintaining long-term supplier relationships is always a priority now", "Tell them you will only increase the order if they offer a significant discount to make it worthwhile"], correct: 1 },
  { type: "mc", id: 15, question: "You're writing a daily operations report for your manager. Which format is most effective?", options: ["A long detailed narrative covering everything that happened during the day from start to finish today", "Key metrics plus highlights, issues, and actions needed presented in a concise organized bullet format", "Just send the raw numbers without any context, because the data should speak for itself without words", "Only flag problems that occurred, because no news is good news and your manager prefers minimal detail"], correct: 1 },
];
