import { MCQuestion } from "./types";

// EXECUTIVE LEVEL — GM, Director, C-Suite, Operations Manager
// All 4 options are similarly comprehensive with multi-step descriptions
// Distribution target: ~11 each across 43 questions

export const PS_EXEC: MCQuestion[] = [
  { type: "mc", id: 1, question: "Your company operates 4 locations. Operating costs: A=32%, B=38%, C=41%, D=35%. Industry benchmark is 33%. Reducing each to benchmark saves: A=Rp 0, B=Rp 75M/yr, C=Rp 120M/yr, D=Rp 30M/yr. Budget for 2 locations. Which two?", options: ["B plus C because they offer the highest combined absolute savings potential among all available pairings", "C plus D, because C has the worst ratio while D offers a relatively quick, easy win to achieve here right", "B plus D, because their improvements are the most realistic to achieve within available budget limits", "C plus B, because C has the worst percentage, while B offers the second-highest absolute savings total"], correct: 0 },
  { type: "mc", id: 2, question: "Evaluating a 5th location. Projected revenue: Rp 1.2B/month. Costs: 34% operating, 28% labor, 12% rent, 10% other. Build-out: Rp 2.5B. What is the monthly net profit and approximate payback period?", options: ["Rp 192M per month with a payback period of approximately thirteen months from launch to full recovery", "Rp 120M per month with a payback period of approximately twenty-one months extending the risk timeline", "Rp 240M per month with a payback period of approximately ten months making this a very aggressive return", "Cannot be determined, because the calculation is missing critical depreciation plus tax data inputs needed"], correct: 0 },
  { type: "mc", id: 3, question: "Team proposes premium service at Rp 888K per customer (current avg Rp 350K). Premium has 40% cost (vs 33% normal). Need 15 customers/day. Capacity is 120. What's the critical question?", options: ["Whether the team can execute fifteen premium services daily without slowing regular service noticeably", "Whether fifteen premium customers at a higher price point will cannibalize regular-spending customers now", "Whether a forty percent cost ratio is acceptable for a premium product given the standard thirty-three", "Both capacity constraints plus cannibalization risk must be analyzed together before making this decision"], correct: 3 },
  { type: "mc", id: 4, question: "Two managers present plans. A wants Rp 500M for facility upgrade (+20% throughput, +Rp 80M/month). B wants Rp 500M for new service area (+Rp 60M/month events). What MOST determines the better investment?", options: ["Current capacity utilization at A's facility versus the actual event demand pipeline that exists for B", "Which manager has a stronger personal track record of delivering on previously projected targets overall", "Which location currently generates higher revenue, since that indicates a stronger foundation for growth", "ROI calculation alone, since A's project returns faster based purely on the projected monthly figures here"], correct: 0 },
  { type: "mc", id: 5, question: "Consolidated P&L: Revenue Rp 4.8B, Costs 35%, Labor 28%, Rent 12%, Marketing 4%, Other 10%. Net margin 11% (Rp 528M). Board wants 15% without cutting revenue. How much must total costs decrease?", options: ["Rp 192M which brings total expenses from Rp 4.272B down to Rp 4.08B to achieve the target margin", "Rp 240M which requires deeper cuts across multiple cost categories to reach the desired margin level", "Rp 168M which represents a relatively modest reduction achievable through efficiency measures alone now", "Rp 288M which requires dramatic restructuring of the cost base beyond what is typically feasible here"], correct: 0 },
  { type: "mc", id: 6, question: "Marketing spend: 40% to Channel A (2.1x return), 30% to B (3.8x), 30% to C (1.4x). Need to cut 25% total. Optimal reallocation?", options: ["Eliminate Channel C entirely since its return is lowest, redistribute the excess savings to Channel B", "Cut twenty-five percent evenly across all three to maintain balanced exposure in the overall marketing mix", "Cut Channel A by fifty percent, while keeping the other two channels at their current spending levels now", "Cut Channel B, since influencer campaigns are hardest to measure accurately, reallocate to digital channels"], correct: 0 },
  { type: "mc", id: 7, question: "One location unprofitable for 6 months (avg loss Rp 35M/month). Lease: 18 months remaining, Rp 300M termination penalty. Staying open costs ~Rp 630M more. Closing: Rp 300M penalty + Rp 80M severance. What do you do?", options: ["Close immediately, because total closure cost of Rp 380M is significantly less than Rp 630M to continue", "Keep it open to attempt a turnaround, since eighteen months provides enough time for meaningful changes", "Negotiate with the landlord to reduce the termination penalty before committing to a final closure decision", "Close immediately while exploring a sublease arrangement to offset some of the early termination penalty"], correct: 3 },
  { type: "mc", id: 8, question: "Scaling from 4 to 10 locations over 3 years. Each manager reports to you directly. At 10 this becomes unsustainable. When do you hire a regional layer?", options: ["At ten locations, because adding management overhead too early reduces margins without sufficient scale now", "Now at four, because the regional manager needs time to build systems before the rapid scaling begins", "At six to seven when direct reporting clearly becomes unmanageable, quality starts declining noticeably", "Never, because standardized technology plus documented procedures can replace middle management effectively"], correct: 2 },
  { type: "mc", id: 9, question: "Investment firm offers Rp 15B for 30% (Rp 50B valuation). Revenue Rp 60B, 12% net margin (Rp 7.2B). Valuation is ~7x earnings. Is this a good deal?", options: ["Yes, because a seven-times earnings multiple is generous for a service business operating in this market right", "No, because companies with strong growth trajectories should command multiples of ten to fifteen or higher", "Depends entirely on what the investor brings beyond capital: networks, operational expertise, exit strategy", "Cannot be evaluated without detailed terms including board seats, drag-along rights, liquidation preferences"], correct: 3 },
  { type: "mc", id: 10, question: "Three concepts proposed: (A) Delivery-only — Rp 300M setup, Rp 200M/month, 8% margin. (B) Full-service — Rp 2B setup, Rp 800M/month, 12% margin. (C) Franchise pilot — Rp 500M setup, Rp 180M/month with royalties, 15% margin. Best risk-adjusted return?", options: ["Concept A, because it has the lowest capital risk paired with the fastest payback period of all three right", "Concept B, because it generates the highest absolute monthly profit at Rp 96M despite highest setup cost", "Concept C, because the highest margin percentage combined with recurring royalty income creates compounding", "Concept C because franchising de-risks the operator side while creating a scalable compounding model here"], correct: 3 },
  { type: "mc", id: 11, question: "Labor cost is 30% of revenue (target 25%). Revenue Rp 1B/month, 45 staff, avg salary Rp 6.67M. Need labor at Rp 250M. Most sustainable approach?", options: ["Cut eight staff members immediately to reduce monthly labor spending by approximately Rp 53M right away right", "Grow revenue by twenty percent to Rp 1.2B per month without adding any additional staff to the payroll right", "Cross-train for flexibility, reduce from forty-five to forty through natural attrition, tie bonuses to output", "Reduce all salaries across the organization by seventeen percent to bring total labor cost to the target right"], correct: 2 },
  { type: "mc", id: 12, question: "Lease negotiation. (A) Fixed Rp 80M/month for 5 years. (B) Rp 50M base + 8% gross revenue (projected Rp 1B/month = Rp 130M). Revenue range: Rp 600M-1.2B. Which is better?", options: ["Always choose A, because fixed costs provide safer, more predictable financial planning over the full term", "Always choose B, because you pay less during low-revenue months providing natural downside protection here", "Choose A if confident revenue exceeds Rp 1B consistently, choose B if you need protection during ramp-up", "Choose B but negotiate a total rent cap at Rp 100M to limit exposure during high-revenue months ahead"], correct: 3 },
];

export const TM_EXEC: MCQuestion[] = [
  { type: "mc", id: 1, question: "This week: (A) Board presentation Friday, (B) Construction 2 weeks behind, (C) GM interview tomorrow, (D) Annual budget planning late, (E) Employee lawsuit filed yesterday. What first?", options: ["Employee lawsuit because legal risk compounds daily, delayed response can significantly worsen the exposure", "Board presentation, because it has the nearest deadline, involves the most important stakeholders directly", "GM interview, because filling leadership positions is always the highest priority in any growing company", "Construction delay, because it represents the largest financial exposure among all five items listed here"], correct: 0 },
  { type: "mc", id: 2, question: "COO, operations head, and marketing director each need 2 hours this week. You have 4 free hours. How do you allocate?", options: ["Prioritize by urgency: the most time-sensitive issue gets two hours, others communicate asynchronously first", "Give each person eighty minutes to be fair, ensure everyone receives adequate face time with you this week", "Cancel all three meetings entirely, focus exclusively on your own individual strategic work for four hours", "Delegate all three meetings to your executive assistant so you can concentrate on higher-priority work now"], correct: 0 },
  { type: "mc", id: 3, question: "New location opening in 8 weeks. Week 3: equipment delivery delayed 3 weeks (arrives week 6, not 3). Soft opening is week 7. What do you do?", options: ["Rent temporary equipment to continue training, negotiate supplier compensation, push the opening back one week", "Push the opening to week ten to ensure there is adequate buffer time for everything to be fully ready now right", "Pressure the supplier with penalty clauses to accelerate delivery, regardless of how realistic the timeline is", "Proceed with the soft opening in week seven as planned using only the equipment currently available on hand"], correct: 0 },
  { type: "mc", id: 4, question: "As CEO you spend 60% on operations, 20% strategy, 20% people. Advisor says reverse the ratio. How do you transition?", options: ["Over six months hire an operations leader, systematize decisions via SOPs, gradually increase coaching time", "Immediately shift the time allocation, because you trust the advice enough to implement the change right away", "Ignore the advice completely, since you know your business best, the current allocation has produced results", "Hire a COO tomorrow, hand over all operational responsibilities immediately without any structured transition"], correct: 0 },
  { type: "mc", id: 5, question: "You get daily reports from 4 managers, weekly from finance, monthly from marketing. Drowning in data. What system do you implement?", options: ["Build a unified dashboard with threshold alerts that only flags items deviating more than ten percent now", "Stop reading all reports entirely, trust the team to escalate anything that genuinely needs your attention", "Hire a dedicated analyst to read everything, summarize it into a concise one-page briefing document daily", "Continue reading everything but reduce time per report by scanning headlines, only diving deep on outliers"], correct: 0 },
  { type: "mc", id: 6, question: "Annual planning should start Q4 but it's mid-Q4 and you haven't started due to a crisis. Board expects plan Jan 1. What's your approach?", options: ["Request a deadline extension from the board, present reasoning that quality planning requires adequate time", "Recycle last year's plan with a fifteen percent growth assumption applied across all revenue projections now", "Run an intensive two-week planning sprint with department heads, focus on the three most critical priorities", "Delegate the entire process to your COO, review their completed draft during the final week before deadline"], correct: 2 },
  { type: "mc", id: 7, question: "Monthly review reveals: (1) Location A missed target 20%, (2) Location B's GM resigned in 2 weeks, (3) Location C has accounting irregularities, (4) Location D wants new concept. How do you triage 48 hours?", options: ["Handle them sequentially in the order received: A first, then B, then C, then D over the next two days right", "GM resignation first, because filling leadership gaps is always more urgent than financial or other concerns", "Accounting irregularities first, then GM resignation, then missed target analysis, then new concept planning", "Missed target first, because revenue shortfalls have the most immediate impact on overall business health"], correct: 2 },
  { type: "mc", id: 8, question: "You manage 5 directors with teams of 8-15 each. One director consistently escalates decisions within their authority. What do you do?", options: ["Make their decisions yourself, since it is faster than coaching them, the business cannot afford slow choices", "Replace them with a naturally decisive person who does not require this level of ongoing management guidance", "Define a clear decision-rights framework specifying what they can decide alone versus what needs your input", "Ignore the escalations entirely until the director independently realizes they must become more self-sufficient"], correct: 2 },
  { type: "mc", id: 9, question: "Major industry event wants your brand (3 days, 2 weeks away). Great brand exposure but team is stretched from a recent location opening. Decision framework?", options: ["Accept immediately, because brand exposure opportunities at this scale rarely come around for your business", "Decline automatically, because compromising existing operations for marketing activities is never worthwhile", "Calculate incremental revenue versus full costs including staff overtime, burnout risk, opportunity cost now", "Accept but staff the event entirely with temporary workers to protect the core team from additional strain"], correct: 2 },
  { type: "mc", id: 10, question: "Building a 3-year strategic plan. How much time should you dedicate and how should the process be structured?", options: ["One full-day offsite with leadership should be sufficient to develop a comprehensive three-year plan now", "Hire an outside consulting firm to develop the plan since they bring objectivity, frameworks, benchmarks", "Two to three half-day workshops over two weeks covering market analysis, strategic options, resource plans", "Write the entire plan yourself over a weekend, since you understand the business better than anyone else"], correct: 2 },
  { type: "mc", id: 11, question: "Planned week: Mon=investor prep, Tue=site visit, Wed=interviews, Thu=finance review, Fri=team event. Tuesday AM: safety incident at a location. How do you restructure?", options: ["Cancel everything for the full week, handle the safety incident personally until it is completely resolved", "Delegate the incident to the location manager, since incident management falls within their direct scope now", "Handle the incident Tuesday by delegating the site visit, keep interviews Wednesday, adjust the rest after", "Cancel Friday's team event, use that day as catch-up buffer for everything displaced earlier in the week"], correct: 2 },
  { type: "mc", id: 12, question: "Company growing 40% YoY. Finance team: 2 people. Operations: 5. Marketing: 4. Budget to hire 3 more. Where?", options: ["One in each department to distribute growth evenly, ensure no single team becomes the critical bottleneck", "Two in operations plus one in finance, since operations is clearly the bottleneck limiting further growth", "Three in operations, because rapid growth means more locations to manage, the team is already overstretched", "One operations, one finance, one HR: infrastructure support systems are needed before you can scale further"], correct: 3 },
  { type: "mc", id: 13, question: "Too many initiatives committed: new location, product overhaul, CRM, training program, brand refresh, supplier renegotiation. Team is burning out. What do you cut?", options: ["Brand refresh, since it is least urgent with no direct short-term revenue impact on the business right now", "Push everything back two months to give the team breathing room before resuming all six initiatives then", "Rank all six by ninety-day revenue impact, reversibility of delay, plus team bandwidth — defer bottom two", "Hire additional people to handle the extra workload, so that nothing on the list needs to be cut or delayed"], correct: 2 },
  { type: "mc", id: 14, question: "As CEO, what percentage of your calendar should be 'unstructured' for thinking, spontaneous conversations, location visits?", options: ["Zero percent, because every minute of a CEO's day should be scheduled productively with measurable outcomes", "Ten to fifteen percent which provides a small emergency buffer without wasting significant productive time right", "Twenty-five to thirty percent because strategic thinking plus culture-building require unscheduled white space", "Fifty percent, because senior leaders should primarily spend their time on thinking rather than doing tasks"], correct: 2 },
  { type: "mc", id: 15, question: "Just promoted someone to GM of your flagship. Talented but first GM role. How do you structure their first 90 days?", options: ["Throw them directly in, because learning through pressure builds resilience faster than any structured program as the recommended course of", "Schedule daily check-ins for all ninety days to catch every mistake before it becomes a serious problem as the recommended course of action", "Days 1-30: shadow outgoing GM, meet every team member. Days 31-60: operate with weekly check-ins. Days 61-90: run independently with targets", "Send them to a formal management training course first before they begin any hands-on work at the location as the recommended course of"], correct: 2 },
  { type: "mc", id: 16, question: "Investors want monthly updates but compiling reports takes 3 days across departments. How do you fix this?", options: ["Tell investors to accept quarterly updates instead, since monthly reporting creates an unreasonable admin burden", "Have each department send their section directly to investors without any centralized review or coordination right", "Hire a dedicated reporting analyst whose full-time responsibility is preparing investor update materials only right", "Automate data collection via dashboards, reduce the report to five key metrics plus narrative, assign one compiler"], correct: 3 },
];

export const COMM_EXEC: MCQuestion[] = [
  { type: "mc", id: 1, question: "Need to announce company-wide layoffs affecting 10% of staff. What's the right approach?", options: ["Send a company-wide email first, then have individual managers follow up with each affected team member", "Let HR handle all communication entirely, since workforce reduction falls within their professional expertise", "Call an all-hands meeting to announce the decision live to everyone at the same time across all locations", "Brief managers first with talking points plus FAQ, then managers tell their teams in person the same day"], correct: 3 },
  { type: "mc", id: 2, question: "Your best-performing GM publicly disagrees with a new policy during a leadership meeting. How do you handle it?", options: ["Shut them down immediately, because discipline must be maintained during all leadership meetings without fail", "Ignore the disagreement completely, move to the next agenda item without addressing what just happened now", "Change the policy to accommodate their concerns, since they are the strongest performer, their input matters", "Acknowledge their perspective, invite discussion afterward, remind the group that final decisions are binding"], correct: 3 },
  { type: "mc", id: 3, question: "Influencer (500K followers) posts a viral negative review (partly inaccurate) about your business. 2M views. How do you respond?", options: ["Post a detailed public rebuttal correcting every inaccuracy point by point to set the record straight now", "Reach out privately to invite them back for a better experience, post a brief professional public response", "Threaten legal action to force removal of the review, demand a retraction of all inaccurate statements now", "Ignore it entirely, wait for the cycle to pass, since most viral content has a very short lifespan anyway"], correct: 1 },
  { type: "mc", id: 4, question: "Pitching to potential investors. They ask: 'Why invest in this industry when the failure rate is 60%?' How do you respond?", options: ["State that you are different, because your product or service quality simply exceeds what competitors offer as the", "Present unit economics proving you are in the surviving 40%: consistent growth, above-average margins, proven playbook", "Explain this is a passion-driven industry where the financial numbers alone do not capture the full story as the", "Note the sixty percent statistic includes small operators, point out it does not apply at your scale level as the"], correct: 1 },
  { type: "mc", id: 5, question: "Location managers come from mixed backgrounds: ex-corporate and promoted-from-within (former frontline). Your communication style should:", options: ["Be identical for everyone, because consistency in leadership communication is paramount for credibility here right", "Adapt: data-driven briefs for ex-corporate managers, hands-on coaching with practical examples for promoted staff", "Default to formal corporate language across the board to raise the professional standard for all managers right", "Default to very simple language across the board so every manager can follow, regardless of their background right"], correct: 1 },
  { type: "mc", id: 6, question: "Quarterly review: CFO recommends closing a financially sound location for strategic brand-positioning reasons. That location's team is in the room. How do you facilitate?", options: ["Do not discuss potential closures while the affected location's team is present in the room at this meeting", "Present data transparently, acknowledge the emotions involved, separate discussion into facts plus options", "Let the CFO handle the entire discussion, since this analysis is their recommendation driving this proposal", "Make the decision before the meeting, announce it as final during the quarterly review without open debate"], correct: 0 },
  { type: "mc", id: 7, question: "You've terminated a GM for misconduct. Rumors are spreading across the company. What's your communication plan?", options: ["Say nothing publicly, because personnel details are private matters that should not be discussed with staff", "Address the team within twenty-four hours: confirm the departure, reassure stability, name interim leader", "Tell everyone exactly what the misconduct was, because full transparency is always the correct policy here", "Send a brief email acknowledging the departure, immediately move on to regular business without elaboration"], correct: 1 },
  { type: "mc", id: 8, question: "Presenting the annual plan to the board. Revenue grew 30% but you missed net margin target by 3 points. How do you frame the narrative?", options: ["Lead with the impressive revenue growth number, since it is the biggest headline, the most positive data point", "Present both results with context explaining why investment in growth infrastructure temporarily reduced margins", "Focus only on what went well during the year, minimize any discussion of the margin shortfall in the slides right", "Blame macroeconomic conditions plus market headwinds for the margin miss, since external factors were the cause"], correct: 1 },
  { type: "mc", id: 9, question: "A journalist contacts you about a rumor regarding your business practices. The practices are legal and industry-standard but could sound controversial. Media response?", options: ["Deny everything completely, regardless of accuracy to protect the company's public image, brand reputation now", "Provide a transparent explanation of the practice, its legality, the industry context, offer further discussion", "Say 'no comment' to avoid giving the journalist any material that could be quoted out of context in print right", "Attack the journalist's credibility, question their motives for pursuing this particular story about you now"], correct: 1 },
  { type: "mc", id: 10, question: "Want to shift culture from top-down to collaborative. What communication changes do you implement?", options: ["Simply announce the culture is now collaborative, expect everyone to adjust their behavior accordingly soon right", "Institute skip-level meetings, create anonymous feedback channels, celebrate employee ideas, model asking first", "Hire an external consultant to redesign the entire organizational communication structure from the ground up", "Remove all hierarchy entirely, implement a completely flat structure where everyone has equal decision power"], correct: 1 },
  { type: "mc", id: 11, question: "Two best location managers in open conflict over shared resources. Morale suffering at both locations. How do you resolve it?", options: ["Pick a side based on who presents the stronger case, allocate resources according to that judgment call now", "Meet each separately to understand their perspective, then facilitate a joint session focused on shared goals", "Transfer one to a different location entirely so they no longer compete for the same pool of shared resources", "Let them sort it out themselves, since both are experienced professionals who should handle conflict independently"], correct: 1 },
  { type: "mc", id: 12, question: "Expanding operations to a new country for the first time. How do you communicate this internally?", options: ["Announce at the annual company event for maximum dramatic impact, employee excitement about the milestone", "Phase communication: leadership first with strategic context, then management with details, then all staff", "Post on social media first, let staff find out through the public channels along with everyone else then", "Only tell people directly involved in the expansion project, keep it confidential from everyone else until launch"], correct: 1 },
  { type: "mc", id: 13, question: "Activist group threatens a social media campaign over alleged labor practices. Claims are exaggerated but not entirely unfounded. How do you prepare?", options: ["Prepare a legal threat to deter them from launching, make clear there will be consequences for defamation", "Audit your practices, fix what you can immediately, prepare factual statements, brief your team, reach out", "Wait to see whether they actually follow through with the campaign before taking any preemptive action now", "Go on the offensive proactively on social media to discredit the group before they can launch their campaign"], correct: 1 },
  { type: "mc", id: 14, question: "Need to convince conservative co-founder to invest Rp 2B in tech (POS, CRM, analytics). They think it's wasteful. How do you build the case?", options: ["Show what competitors are doing with technology, argue that falling behind will cost more in the long run right", "Present a detailed business case showing the current cost of inefficiency versus projected ROI from the tech", "Tell them directly they are behind the times, stress that the business will fail without modernizing systems", "Start with a small pilot project, let measurable results speak for themselves before requesting full investment"], correct: 3 },
  { type: "mc", id: 15, question: "Need to communicate a major strategic pivot to the entire company. What are the essential elements?", options: ["Simply announce the change, move directly to implementation, since lengthy explanations slow down execution right", "Cover the WHY with data, the WHAT specifically changing, WHEN timeline, HOW for each team, WHO to ask questions", "Write a detailed ten-page strategy document covering every aspect of the pivot for comprehensive understanding", "Give a brief motivational speech about embracing change, trust the team to work out the operational details right"], correct: 1 },
];
