// Indonesian translations for Staff-level questions
// Option order matches the English file after rebalancing

export const PS_STAFF_ID: { question: string; options: string[] }[] = [
  { question: "Pelanggan menerima pesanan yang salah. Apa yang harus Anda lakukan PERTAMA?", options: ["Minta maaf dengan tulus dan konfirmasi apa yang pelanggan pesan dari menu aslinya tadi sebelumnya", "Tanya rekan kerja untuk mengecek tiket pesanan sebelum mengatakan apapun kepada pelanggan tentang ini", "Tawarkan diskon penuh untuk bill pelanggan dan biarkan mereka menyimpan item yang salah itu juga", "Informasikan pelanggan bahwa kesalahan pesanan kadang terjadi dan pesanan benar akan segera disiapkan"] },
  { question: "Anda melihat persediaan di station Anda hampir habis saat periode sibuk. Apa yang harus dilakukan?", options: ["Informasikan supervisor dan cepat restock dari persediaan cadangan sambil tetap menjalankan tugas Anda", "Berhenti dari apa yang sedang Anda kerjakan dan langsung pergi ke gudang untuk mengisi ulang stok semua", "Tunggu sampai persediaan benar-benar habis sebelum meninggalkan station Anda untuk mengambil stok baru", "Lanjut bekerja seperti biasa dan sebutkan persediaan rendah ke shift berikutnya saat mereka tiba nanti"] },
  { question: "Pelanggan membeli 3 item @ Rp 35.000 dan 2 item @ Rp 85.000. Berapa subtotalnya?", options: ["Rp 275.000", "Rp 240.000", "Rp 255.000", "Rp 205.000"] },
  { question: "Anda tidak sengaja merusak barang pribadi pelanggan. Respons terbaik?", options: ["Tunggu dulu apakah pelanggan menyadari kerusakan sebelum Anda menyampaikan masalah tersebut ke mereka", "Tawarkan untuk membayar perbaikan dari gaji sendiri untuk menunjukkan bahwa Anda bertanggung jawab penuh", "Segera minta maaf dan beritahu supervisor Anda supaya mereka bisa menangani situasinya dengan tepat", "Jelaskan ke pelanggan bahwa itu hal kecil dan kemungkinan tidak menyebabkan kerusakan permanen apapun"] },
  { question: "Bisnis Anda sedang penuh kapasitas tapi pelanggan walk-in minta dilayani. Apa yang Anda katakan?", options: ["Minta maaf bahwa kapasitas penuh dan tawarkan memasukkan mereka ke daftar tunggu dengan estimasi waktu", "Sarankan mereka coba bisnis lain di dekat sini karena tidak akan ada ketersediaan untuk beberapa saat lagi", "Biarkan pelanggan menunggu di area depan tanpa memberikan estimasi waktu tunggu yang spesifik sama sekali", "Sarankan mereka kembali lagi nanti malam saat mungkin ada tempat kosong yang tersedia untuk mereka nanti"] },
  { question: "Anda melihat rekan kerja mengambil produk perusahaan tanpa izin. Apa yang harus dilakukan?", options: ["Laporkan apa yang Anda lihat ke supervisor secara privat dan biarkan mereka menanganinya dengan benar", "Tegur rekan kerja keras-keras di depan semua orang supaya mereka tahu itu salah dan tidak mengulangi", "Beritahu rekan kerja lain tentang kejadian itu supaya mereka bisa ikut membantu mengawasi situasinya", "Abaikan sepenuhnya karena itu bukan tanggung jawab Anda dan Anda tidak mau menimbulkan masalah di sini"] },
  { question: "Sebuah tugas membutuhkan 200 gram bahan per batch. Anda perlu menyiapkan 5 batch. Berapa bahan yang dibutuhkan?", options: ["750g", "1.200g", "1.000g", "500g"] },
  { question: "Pelanggan memberitahu Anda bahwa mereka punya alergi parah. Apa yang dilakukan?", options: ["Hilangkan alergen dari pesanan sendiri sebelum menyajikan tanpa memberitahu siapapun tentang hal itu", "Catat alergi dengan jelas di pesanan, beritahu tim terkait, dan verifikasi sebelum menyajikan ke mereka", "Bilang ke pelanggan bahwa kebanyakan produk Anda kemungkinan tidak mengandung alergen tersebut sama sekali", "Sarankan pelanggan mengunjungi bisnis lain yang khusus menangani produk aman alergi demi keamanan mereka"] },
  { question: "Saat merapikan area kerja, Anda menemukan barang pribadi pelanggan yang tertinggal. Apa yang dilakukan?", options: ["Biarkan di tempat Anda menemukannya karena pelanggan kemungkinan akan kembali mengambilnya segera nanti", "Coba buka atau periksa barang tersebut untuk mengidentifikasi pemiliknya supaya bisa menghubungi mereka", "Serahkan ke supervisor atau bawa ke area lost-and-found yang sudah ditentukan dengan segera sekarang juga", "Simpan di tas Anda untuk diamankan dan tunggu apakah ada yang datang menanyakannya belakangan hari ini"] },
  { question: "Shift Anda mulai jam 10:00 tapi Anda terjebak macet dan akan tiba 15 menit terlambat. Apa yang harus dilakukan?", options: ["Hubungi supervisor sesegera mungkin untuk memberitahu perkiraan waktu kedatangan Anda hari ini kepada mereka", "Minta rekan kerja untuk absen untuk Anda supaya tidak tercatat terlambat di sistem kehadiran kantor hari", "Tiba terlambat dan jelaskan situasi macetnya ke supervisor saat mereka menanyakan keterlambatan Anda nanti", "Izin sakit saja daripada tiba terlambat karena itu terlihat lebih baik di catatan kehadiran Anda secara umum"] },
  { question: "Pelanggan bertanya tentang bahan atau fitur yang Anda tidak yakin. Apa yang dilakukan?", options: ["Bilang Anda tidak yakin tapi tawarkan untuk mengecek ke orang yang tepat dan kembali ke mereka segera", "Berikan tebakan terbaik Anda supaya pelanggan tidak perlu menunggu jawaban pasti dari orang lain nantinya", "Bilang ke pelanggan Anda tidak tahu dan sarankan mereka mencarinya sendiri secara online karena lebih cepat", "Bilang tidak untuk amannya karena lebih baik kurang berjanji daripada memberikan informasi yang salah ke mereka"] },
  { question: "Mendekati akhir shift, Anda melihat tugas kebersihan yang sudah lama terabaikan. Apa yang dilakukan?", options: ["Tutupi supaya tidak terlihat dan biarkan shift berikutnya menemukan dan menanganinya nanti saat mereka kerja", "Tangani sekarang karena menjaga standar adalah tanggung jawab semua orang terlepas dari waktu shift-nya", "Tinggalkan untuk shift berikutnya karena jam kerja Anda hampir selesai untuk hari ini dan sudah waktunya pulang", "Pura-pura tidak melihatnya karena menyebutkan berarti pekerjaan tambahan untuk diri Anda sendiri sekarang ini"] },
];

export const TM_STAFF_ID: { question: string; options: string[] }[] = [
  { question: "Anda tiba untuk shift. Apa yang harus dilakukan PERTAMA?", options: ["Langsung mulai melayani pelanggan supaya tidak membuang waktu kerja yang produktif sedikitpun dari awal", "Cek station, review catatan dari shift sebelumnya, dan siapkan peralatan kerja Anda dengan lengkap baik", "Ke break room dan minum kopi dulu sebelum melakukan apapun untuk menyiapkan diri memulai hari kerja ini", "Ngobrol dengan rekan kerja tentang apa yang terjadi kemarin supaya tahu perkembangan terbaru semuanya"] },
  { question: "Tiga tugas butuh perhatian bersamaan: Tugas A adalah permintaan pelanggan baru, Tugas B ada item sensitif waktu siap diantarkan, Tugas C adalah permintaan pembayaran. Urutan apa?", options: ["Tugas A dulu, lalu Tugas B, lalu Tugas C karena permintaan baru harus selalu didahulukan setiap saat", "Tugas C dulu, lalu B, lalu A karena pembayaran membersihkan pelanggan dengan paling efisien untuk semua", "Tugas B dulu karena itemnya akan menurun kualitasnya, lalu Tugas A, lalu Tugas C untuk pembayaran akhir", "Tugas B dulu untuk cegah penurunan kualitas, lalu Tugas C untuk efisiensi, lalu Tugas A paling terakhir"] },
  { question: "Anda perlu menyelesaikan 6 tugas serupa. Peralatan Anda bisa menangani 2 sekaligus. Cara tercepat?", options: ["Selesaikan satu per satu supaya setiap tugas mendapat perhatian penuh dan fokus dari Anda seorang diri", "Proses berpasangan 2-2, gunakan waktu tunggu antar batch untuk menyiapkan bahan untuk batch selanjutnya", "Kerjakan semua 6 sekaligus dengan cara terburu-buru secepat mungkin yang bisa Anda capai dan selesaikan", "Minta orang lain membantu supaya Anda bisa membagi pekerjaan secara merata antara dua orang yang kerja"] },
  { question: "Supervisor menugaskan tugas baru, tapi Anda sedang membantu pelanggan. Apa yang dilakukan?", options: ["Berhenti membantu pelanggan segera dan pergi mengerjakan apa yang supervisor minta Anda lakukan barusan", "Selesaikan membantu pelanggan dulu, lalu segera mulai tugas yang ditugaskan setelah itu langsung dikerjakan", "Bilang ke supervisor Anda terlalu sibuk untuk menerima tanggung jawab tambahan apapun saat ini sekarang", "Abaikan permintaan supervisor karena pelanggan yang sedang Anda bantu saat ini lebih prioritas untuk dilayani"] },
  { question: "30 menit sebelum buka dan Anda punya tiga tugas setup: Tugas A (20 menit), Tugas B (10 menit), Tugas C (5 menit). Total 35 menit. Bisa selesai tepat waktu?", options: ["Tidak — panggil staf tambahan karena memang tidak ada cukup waktu untuk menyelesaikan semuanya sama sekali", "Ya — skip Tugas C sepenuhnya karena itu yang paling tidak penting dari tiga tugas yang terdaftar itu", "Tidak — tugasnya jelas berjumlah 35 menit yang lebih dari 30 menit yang tersedia untuk persiapan ini", "Ya — gabungkan Tugas B dengan Tugas A sambil bergerak antar area untuk menghemat waktu tumpang tindih"] },
  { question: "Saat periode sibuk, pelanggan reguler mengajak ngobrol. Anda punya beberapa pelanggan lain menunggu. Apa yang dilakukan?", options: ["Ngobrol dengan mereka karena pelanggan reguler itu penting dan layak mendapat perhatian khusus selalu saat", "Sapa dengan sopan, jelaskan akan kembali sebentar, dan layani pelanggan yang menunggu terlebih dahulu itu", "Bilang ke reguler untuk datang lagi saat tidak sibuk karena Anda tidak bisa bicara sekarang saat ini", "Abaikan reguler dan layani pelanggan lain tanpa mengatakan apapun kepada mereka sama sekali tentang ini"] },
  { question: "Tugas closing: pel lantai (15 menit), hitung kas (10 menit), lap permukaan (10 menit), buang sampah (5 menit). Urutan paling efisien?", options: ["Kas dulu, permukaan, sampah, lalu pel terakhir supaya lantai tetap bersih dan mengering dengan baik sekali", "Pel dulu, lalu permukaan, sampah, dan kas terakhir karena lantai butuh waktu paling lama untuk mengering", "Sampah dulu, lalu permukaan, lalu kas, dan terakhir pel di akhir proses closing malam ini sepenuhnya sekali", "Permukaan dulu, lalu pel, lalu sampah, dan kas terakhir untuk mengakhiri dengan menghitung register kasir itu"] },
  { question: "Rekan kerja minta Anda cover station mereka 5 menit, tapi station Anda sendiri sibuk. Apa yang dilakukan?", options: ["Bilang iya dan coba cover kedua station bersamaan meski Anda sudah kewalahan dengan pekerjaan sendiri saat", "Jelaskan station Anda sibuk sekarang dan sarankan mereka minta supervisor untuk pengaturan coverage tepat", "Cover station mereka dan abaikan punya Anda karena mereka minta duluan dan Anda harus saling membantu", "Bilang tidak secara blak-blakan dan pergi tanpa menawarkan solusi alternatif apapun untuk membantu mereka"] },
  { question: "Ada pengiriman sensitif waktu yang siap, tapi Anda juga perlu mengambil pesanan pelanggan baru. Pengiriman akan menurun kualitasnya jika ditunda. Mana prioritasnya?", options: ["Ambil pesanan pelanggan baru dulu karena lebih cepat dan bisa memulai pelayanan mereka lebih awal segera", "Tangani pengiriman sensitif waktu segera, lalu ambil pesanan pelanggan baru langsung setelahnya selesai", "Antarkan setengah pengiriman, ambil pesanan dari pelanggan, lalu antarkan sisanya yang masih tertinggal", "Minta anggota tim lain membantu salah satu dari dua tugas tersebut jika ada yang tersedia di dekat sini"] },
  { question: "Anda ditugaskan tugas back-of-house, tapi area customer-facing tiba-tiba sibuk. Apa yang dilakukan?", options: ["Selesaikan tugas back-of-house sepenuhnya sebelum keluar membantu pelanggan sama sekali yang menunggu itu", "Bantu area pelanggan saat rush, lalu selesaikan tugas back-of-house begitu situasi mulai mereda kembali", "Tinggalkan tugas back-of-house sepenuhnya dan jangan kembali lagi untuk sisa shift Anda hari ini sama sekali", "Komplain ke manajer bahwa Anda punya terlalu banyak tugas yang ditugaskan untuk satu orang mengerjakannya"] },
  { question: "Anda melihat station persediaan hampir kosong saat membantu pelanggan. Apa yang dilakukan?", options: ["Berhenti di tengah pelayanan untuk mengisi ulang station itu segera sebelum melakukan hal lain saat ini", "Biarkan saja sepenuhnya karena restock bukan bagian spesifik dari deskripsi pekerjaan Anda yang ditugaskan", "Selesaikan melayani pelanggan, lalu isi ulang semua station persediaan di section Anda sebelum lanjut kerja", "Tunggu sampai orang lain menyadarinya kosong dan biarkan mereka komplain sebelum Anda mengisi ulang stok"] },
  { question: "Shift Anda selesai jam 15:00 tapi rombongan besar baru tiba jam 14:45. Apa yang harus dilakukan?", options: ["Pulang tepat jam 15:00 karena shift sudah selesai dan Anda tidak berkewajiban untuk tinggal lebih lama hari", "Tolak membantu mereka sama sekali karena mereka tiba terlalu dekat dengan akhir shift kerja Anda hari ini", "Ambil permintaan awal mereka dan serahkan ke anggota tim berikutnya dengan briefing yang jelas dan lengkap", "Tunggu sampai sepenuhnya selesai meski itu berarti bekerja berjam-jam melewati jadwal Anda yang ditentukan"] },
  { question: "Peralatan penting rusak saat periode sibuk. Apa yang harus dilakukan?", options: ["Berhenti dari semua tugas lain dan coba perbaiki peralatan sendiri meski tanpa pelatihan yang memadai ini", "Informasikan supervisor, lalu mulai gunakan metode backup yang tersedia untuk menjaga operasional berjalan", "Tunggu teknisi reparasi profesional datang sebelum melakukan apapun di station Anda yang sedang bermasalah", "Bilang tim untuk berhenti menggunakan area kerja sepenuhnya sampai seseorang memperbaiki peralatan yang rusak"] },
  { question: "Anda punya istirahat 15 menit tapi ada rush pelanggan. Apa yang dilakukan?", options: ["Ambil istirahat penuh karena Anda berhak dan perlu istirahat untuk tetap perform baik sepanjang hari kerja", "Tanya supervisor apakah bisa menunda istirahat 10 menit sampai rush reda dan situasi lebih terkendali itu", "Skip istirahat sepenuhnya karena kebutuhan bisnis harus selalu didahulukan di atas kebutuhan pribadi kapanpun", "Ambil istirahat cepat 5 menit saja dan berharap rush mereda saat Anda kembali ke area kerja nanti setelah"] },
  { question: "Minggu pertama Anda. Sudah diajari sebuah proses sekali tapi belum percaya diri. Pelanggan memintanya. Apa yang dilakukan?", options: ["Coba sendiri tanpa panduan karena seharusnya Anda bisa mengerjakannya sendiri tanpa bantuan orang lain itu", "Minta rekan kerja berpengalaman membimbing Anda atau mengawasi saat Anda melakukan prosesnya langkah demi langkah", "Bilang ke pelanggan Anda tidak bisa karena masih baru dan belum sepenuhnya mempelajari proses tersebut ini", "Kerjakan sesuatu yang berbeda dan berharap pelanggan tidak menyadari bahwa Anda mengganti dengan yang lain"] },
  { question: "Dua pelanggan butuh bantuan Anda bersamaan. Satu terlihat tidak sabar, yang lain santai. Siapa yang didekati dulu?", options: ["Yang tidak sabar karena mereka lebih mungkin mengeskalasi komplain jika tidak segera dibantu terlebih dahulu", "Yang santai karena mereka lebih mudah ditangani dan Anda bisa menyelesaikan urusan mereka dengan cepat segera", "Siapapun yang secara fisik paling dekat dengan Anda saat ini terlepas dari bagaimana perasaan mereka terlihat", "Akui keduanya dengan kontak mata dan anggukan, lalu datangi siapa yang sudah menunggu paling lama duluan"] },
];

export const COMM_STAFF_ID: { question: string; options: string[] }[] = [
  { question: "Pelanggan minta rekomendasi tapi Anda tidak yakin apa yang paling populer hari ini. Apa yang dikatakan?", options: ["Bilang semuanya bagus dan mereka tidak bisa salah pilih dengan apapun yang tersedia di daftar saat ini", "Sebutkan favorit pribadi dan tawarkan untuk mengecek item unggulan hari ini untuk mereka juga tentunya", "Bilang Anda tidak tahu karena Anda cuma kerja di sini dan tidak bisa memberikan saran pribadi apapun", "Bilang mereka untuk pilih saja apapun karena semua pilihannya pada dasarnya kualitasnya sama saja sebenarnya"] },
  { question: "Pelanggan berbicara sangat pelan dan Anda tidak dengar permintaan mereka di lingkungan yang ramai. Apa yang dilakukan?", options: ["Tebak apa yang mereka katakan dan lanjutkan berdasarkan interpretasi terbaik Anda atas permintaan mereka", "Mendekat dengan sopan, minta mereka mengulangi, dan konfirmasi kembali apa yang Anda dengar dengan jelas", "Teriak dari counter meminta mereka berbicara lebih keras supaya semua orang di sekitar juga bisa mendengar", "Tulis sesuatu yang kira-kira dan berharap cukup dekat dengan apa yang mereka minta sebenarnya supaya benar"] },
  { question: "Supervisor memberi feedback: 'Kamu perlu lebih cepat saat periode sibuk.' Bagaimana seharusnya merespons?", options: ["Terima kasih atas feedbacknya dan tanya apakah ada area spesifik yang bisa Anda fokuskan untuk perbaikan", "Bilang Anda sudah berusaha semaksimal mungkin dan tidak ada lagi yang bisa Anda ubah secara realistis saat", "Tunjukkan bahwa anggota tim lain juga lambat jadi tidak adil kalau Anda saja yang disinggung sendirian", "Diam, pergi, dan terus melakukan persis apa yang sudah Anda lakukan tanpa perubahan apapun kedepannya ini"] },
  { question: "Anak pelanggan berlarian di tempat bisnis dan menciptakan bahaya keselamatan. Bagaimana mengatasinya?", options: ["Bilang langsung ke anak untuk berhenti berlari dan duduk karena mereka bisa terluka serius jika jatuh", "Abaikan situasinya sepenuhnya karena bukan tanggung jawab Anda untuk mengurus anak pelanggan di sini ini", "Dekati orang tua dengan sopan dan jelaskan kekhawatiran keselamatan, minta mereka agar anak tetap duduk", "Komplain ke rekan kerja tentang situasinya dan berharap orang lain akhirnya menanganinya daripada Anda saja"] },
  { question: "Anda salah memberikan kembalian Rp 10.000 kurang ke pelanggan. Mereka belum sadar. Apa yang dilakukan?", options: ["Diam saja karena mereka tidak sadar dan jumlahnya relatif kecil dan tidak terlalu signifikan untuk diributkan", "Tunggu dulu apakah mereka kembali dan komplain tentang hal itu sebelum Anda mengambil tindakan koreksi", "Dekati pelanggan, minta maaf atas kesalahan tersebut, dan berikan sisa kembalian yang benar kepada mereka", "Bilang supervisor tentang kesalahan tapi jangan dekati pelanggan secara langsung untuk memberitahu mereka ini"] },
  { question: "Rekan kerja bersikap kasar pada Anda di depan pelanggan. Respons terbaik?", options: ["Balas dengan kasar yang setara supaya mereka tahu Anda tidak terima diperlakukan seperti itu secara publik", "Tetap profesional, jangan bereaksi di depan pelanggan, dan diskusikan secara privat dengan rekan setelahnya", "Laporkan mereka ke manajer segera di situ juga di depan semua pelanggan yang sedang melihat kejadian itu", "Tinggalkan area kerja untuk menenangkan diri dan biarkan pelanggan menunggu tanpa pelayanan apapun dahulu"] },
  { question: "Pelanggan bertanya tentang sesuatu di luar area pengetahuan Anda. Apa yang dikatakan?", options: ["Karang jawaban yang terdengar masuk akal supaya pelanggan tidak berpikir Anda tidak kompeten di pekerjaan", "Bilang itu bukan departemen Anda dan mereka perlu mencari orang lain untuk menjawab pertanyaan mereka", "Bilang Anda tidak yakin tapi akan mencarikan orang yang tepat untuk memberikan jawaban yang akurat segera", "Bilang Anda tidak tahu sama sekali dan sarankan mereka cari di internet sendiri karena itu lebih cepat ini"] },
  { question: "Operasional berjalan 15 menit di belakang jadwal. Pelanggan bertanya tentang pesanan mereka. Apa yang dikatakan?", options: ["Bilang Anda tidak tahu apa penyebab keterlambatan karena itu bukan area tanggung jawab Anda secara spesifik", "Terima kasih atas kesabaran mereka, jelaskan ada sedikit keterlambatan, dan tawarkan sesuatu selagi menunggu", "Bilang pesanan akan datang kalau sudah siap dan tidak ada yang bisa Anda lakukan untuk mempercepat prosesnya", "Hindari area mereka sepenuhnya sampai pesanan siap supaya Anda tidak perlu menjelaskan apapun kepada mereka"] },
  { question: "Anda mendengar pelanggan menyatakan ketidakpuasan ke teman mereka, bukan langsung ke Anda. Haruskah Anda ikut campur?", options: ["Tidak — mereka tidak komplain ke Anda langsung jadi akan intrusif kalau Anda ikut terlibat dalam hal ini", "Dekati dengan lembut dan tanya apakah ada yang bisa Anda bantu untuk memperbaiki pengalaman mereka ini", "Bilang tim apa yang pelanggan katakan supaya semua tahu tapi jangan bicara langsung ke pelanggan tersebut", "Pura-pura tidak mendengar apapun dan lanjutkan pekerjaan Anda seolah tidak ada yang tidak biasa terjadi itu"] },
  { question: "Di akhir shift, anggota tim berikutnya bertanya tentang beban kerja Anda saat ini. Serah terima terbaik?", options: ["Bilang semuanya baik-baik saja dan biarkan mereka mengerjakannya sendiri saat mereka mulai bekerja nanti", "Jelaskan singkat status setiap tugas aktif, item yang tertunda, dan permintaan khusus yang perlu dicatat", "Tunjuk area kerja dan ucapkan good luck tanpa memberikan detail spesifik yang berguna apapun untuk mereka", "Tulis laporan sangat detail berlembah-lembah yang mencakup setiap hal yang terjadi hari ini sepenuhnya ini"] },
  { question: "Sekelompok pelanggan sangat berisik dan mengganggu orang lain di sekitarnya. Bagaimana mendekati mereka?", options: ["Bilang tegas untuk segera diam atau mereka harus pergi meninggalkan tempat usaha ini sekarang juga segera", "Dekati dengan senyum, akui mereka sedang bersenang-senang, dan sopan minta mereka menurunkan volume suara", "Abaikan situasinya sepenuhnya karena mereka pelanggan yang membayar dan Anda tidak bisa menyuruh mereka itu", "Pindahkan pelanggan lain yang terdampak ke area berbeda daripada mengonfrontasi kelompok yang berisik itu"] },
  { question: "Anda baru dan tidak yakin apakah produk atau layanan tertentu tersedia. Pelanggan bertanya. Apa yang dikatakan?", options: ["Bilang tidak untuk amannya karena lebih baik menolak permintaan daripada memberikan informasi yang salah ini", "Akui Anda baru dan tidak tahu apa-apa sama sekali yang mana itulah mengapa tidak bisa menjawab pertanyaan", "Bilang Anda ingin memberikan informasi yang akurat dan akan mengecek ke tim Anda segera untuk memastikan", "Serahkan brosur atau menu diam-diam dan pergi tanpa menawarkan bantuan verbal apapun sama sekali ke mereka"] },
  { question: "Pelanggan membuat permintaan pribadi yang tidak biasa. Kebijakan perusahaan tidak jelas mengenai hal itu. Apa yang dilakukan?", options: ["Setuju segera tanpa mengecek karena pelanggan harus selalu mendapatkan apa yang mereka minta setiap saat", "Tolak permintaan mentah-mentah karena kalau tidak ada kebijakan jelas maka kemungkinan tidak diperbolehkan", "Sopan bilang ke pelanggan Anda senang membantu dan hanya perlu memverifikasi dulu dengan supervisor Anda", "Abaikan permintaan sepenuhnya dan ganti topik ke hal lain yang bisa Anda bantu untuk mereka saat ini saja"] },
  { question: "Saat briefing tim, supervisor menjelaskan aturan baru yang tidak Anda setujui. Apa yang dilakukan?", options: ["Debat di depan seluruh tim karena perspektif Anda layak didengar sekarang juga pada saat briefing ini hari", "Ikuti aturannya untuk saat ini, lalu temui supervisor secara privat untuk menyampaikan kekhawatiran Anda", "Abaikan aturan kapanpun tidak ada yang mengawasi karena Anda tahu cara yang lebih baik melakukannya ini", "Komplain ke rekan kerja setelah briefing dan dorong mereka untuk juga menolak aturan baru yang berlakukan"] },
  { question: "Pelanggan memberi Anda tip besar secara personal, tapi perusahaan punya kebijakan bagi tip. Apa yang dilakukan?", options: ["Simpan seluruh jumlahnya karena pelanggan secara spesifik bermaksud memberikannya untuk Anda bukan orang lain", "Bagi hanya dengan rekan terdekat karena kebijakannya terasa tidak adil untuk individu yang berkinerja tinggi", "Terima kasih hangat ke pelanggan dan ikuti kebijakan bagi tip perusahaan yang berlaku untuk semua orang", "Berikan seluruh jumlah ke manajer dan biarkan mereka memutuskan bagaimana harus didistribusikan ke semua staf"] },
];
